### ISSUE TITLE
Pugixml 1.5 failes to compile on Win7 x64 MinGW 4.7.1 with -std=c++11

### ISSUE THREAD

**Issue by Shelim** [zeux/pugixml#24]
When compiling Pugixml 1.5 on MinGW 4.7.1. on Win7 x64 Home Premium got:

```
pugixml.cpp: In function 'pugi::xml_parse_status pugi::impl::{anonymous}::get_file_size(FILE*, size_t&)':
pugixml.cpp:4000:11: error: 'off64_t' does not name a type
pugixml.cpp:4002:29: error: 'fseeko64' was not declared in this scope
pugixml.cpp:4003:3: error: 'length_type' was not declared in this scope
pugixml.cpp:4003:15: error: expected ';' before 'length'
pugixml.cpp:4015:7: error: 'length' was not declared in this scope
pugixml.cpp:4018:39: error: 'length' was not declared in this scope
pugixml.cpp:4020:19: error: expected type-specifier before 'length_type'
pugixml.cpp:4020:19: error: expected '>' before 'length_type'
pugixml.cpp:4020:19: error: expected '(' before 'length_type'
pugixml.cpp:4020:51: error: expected ')' before 'return'
pugixml.cpp: In function 'FILE* pugi::impl::{anonymous}::open_file_wide(const wchar_t*, const wchar_t*)':
pugixml.cpp:4246:28: error: '_wfopen' was not declared in this scope
```

Command used for compilation:

`mingw32-g++.exe -march=pentium4 -std=c++11 -w -fno-strict-aliasing -D__STDC_CONSTANT_MACROS -fexpensive-optimizations -O2 -DNDEBUG -D_WINDOWS -DUNICODE -D_UNICODE -c C:\pugixml\src\pugixml.cpp -o C:\pugixml\build\pugixml.o`

I've googled a bit and it seems to be long standing compiler bug:
http://sourceforge.net/p/mingw/bugs/2024/

Is it possible to adopt workaround for it in Pugixml 1.5?
