### ISSUE TITLE
Fallthrough errors with debug build with GCC 9.2.0

### ISSUE THREAD

**Issue by aeslaughter** [zeux/pugixml#331]
GCC 9.2 indicates that there is some potential problems with return statements.

```
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:11723:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
11723 |         if (_rettype == xpath_type_boolean)
      |         ^~
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:11728:7: note: here
11728 |       default:
      |       ^~~~~~~
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C: In member function 'double pugi::impl::{anonymous}::xpath_ast_node::eval_number(const pugi::impl::{anonymous}::xpath_context&, const pugi::impl::{anonymous}::xpath_stack&)':
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:11858:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
11858 |         if (_rettype == xpath_type_number)
      |         ^~
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:11863:7: note: here
11863 |       default:
      |       ^~~~~~~
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C: In member function 'pugi::impl::{anonymous}::xpath_string pugi::impl::{anonymous}::xpath_ast_node::eval_string(const pugi::impl::{anonymous}::xpath_context&, const pugi::impl::{anonymous}::xpath_stack&)':
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:12162:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
12162 |         if (_rettype == xpath_type_string)
      |         ^~
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:12167:7: note: here
12167 |       default:
      |       ^~~~~~~
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C: In member function 'pugi::impl::{anonymous}::xpath_node_set_raw pugi::impl::{anonymous}::xpath_ast_node::eval_node_set(const pugi::impl::{anonymous}::xpath_context&, const pugi::impl::{anonymous}::xpath_stack&, pugi::impl::{anonymous}::nodeset_eval_t)':
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:12319:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
12319 |         }
      |         ^
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:12323:7: note: here
12323 |       default:
      |       ^~~~~~~
cc1plus: all warnings being treated as errors
```

**Comment by zeux** [comment]
Can you clarify a couple of things?

- Which exact version of gcc is that?
- Can you attach the pugixml.C file you're using?

The reason I ask is that my line numbers don't match yours, but I don't get this using

> gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)

The construct that prevents gcc from emitting fallthrough warnings is actually the `// fallthrough` comment, so I'm wondering if your file for some reason comes with stripped comments.

**Comment by aeslaughter** [comment]
Interesting, I bet it is the clang-format that was applied to the file when I put it into our contrib directory. I will let you know next week when I get back to this. Thanks!

**Comment by aeslaughter** [comment]
I removed my accidental clang format and I am still seeing the errors with v1.10 and the line numbers are now matching

## System
```
[Ubuntu-16][~]> lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
[Ubuntu-16][~]> gcc --version
gcc (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
## Link to first Error 

https://github.com/zeux/pugixml/blob/3c59df555b93a7650ae0056da34bacde93f4ef8f/src/pugixml.cpp#L10352

## Actual Error message
```
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C: In member function 'bool pugi::impl::{anonymous}::xpath_ast_node::eval_boolean(const pugi::impl::{anonymous}::xpath_context&, const pugi::impl::{anonymous}::xpath_stack&)':
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:10352:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
10352 |     if (_rettype == xpath_type_boolean)
      |     ^~
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:10357:4: note: here
10357 |    default:
      |    ^~~~~~~
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C: In member function 'double pugi::impl::{anonymous}::xpath_ast_node::eval_number(const pugi::impl::{anonymous}::xpath_context&, const pugi::impl::{anonymous}::xpath_stack&)':
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:10487:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
10487 |     if (_rettype == xpath_type_number)
      |     ^~
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:10492:4: note: here
10492 |    default:
      |    ^~~~~~~
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C: In member function 'pugi::impl::{anonymous}::xpath_string pugi::impl::{anonymous}::xpath_ast_node::eval_string(const pugi::impl::{anonymous}::xpath_context&, const pugi::impl::{anonymous}::xpath_stack&)':
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:10771:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
10771 |     if (_rettype == xpath_type_string)
      |     ^~
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:10776:4: note: here
10776 |    default:
      |    ^~~~~~~
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C: In member function 'pugi::impl::{anonymous}::xpath_node_set_raw pugi::impl::{anonymous}::xpath_ast_node::eval_node_set(const pugi::impl::{anonymous}::xpath_context&, const pugi::impl::{anonymous}::xpath_stack&, pugi::impl::{anonymous}::nodeset_eval_t)':
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:10921:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
10921 |     }
      |     ^
/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.C:10925:4: note: here
10925 |    default:
      |    ^~~~~~~
cc1plus: all warnings being treated as errors
/opt/civet/build_0/moose/framework/build.mk:118: recipe for target '/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.x86_64-pc-linux-gnu.opt.lo' failed
make: *** [/opt/civet/build_0/moose/framework/contrib/pugixml/src/pugixml.x86_64-pc-linux-gnu.opt.lo] Error 1
make: *** Waiting for unfinished jobs....
```

## Link to Error on test system
You can see the error on one of our test systems here: https://civet.inl.gov/job/465143/

**Comment by zeux** [comment]
I still can't reproduce this short of using -Wimplicit-fallthrugh=4 (which is not automatically enabled by any other gcc warning flag I know of).

However, I don't think we really need to rely on fallthrough here, so I can change the code accordingly.

**Comment by aeslaughter** [comment]
Thanks for looking into this, we use very strict warnings in our builds. Just FYI, I was able to get things to compile with the changes listed here.

https://github.com/idaholab/moose/pull/14677/commits/551c657464699bec16ec145257aa4caf502fbe15
